services:
  app:
    image: ruby:3.4.4
    tty: true
    stdin_open: true
    env_file:
      - .dev.env
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails s -b 0.0.0.0"

  db:
    image: mariadb:latest
    tty: true
    stdin_open: true
    env_file:
      - .dev.env
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    tty: true
    stdin_open: true
    env_file:
      - .dev.env
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-vol:
