apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ruby:3.3.6 # ビルドするDockerイメージを使用してください
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "development"
        volumeMounts:
        - name: app-volume
          mountPath: /app
        command:
        - bash
        - -c
        - |
          rm -f /app/tmp/pids/server.pid &&
          rm -f /app/public/assets &&
          gem cleanup &&
          bundle install -j4 &&
          rails s -b 0.0.0.0
      volumes:
      - name: app-volume
        hostPath:
          path: /host_mnt/c/Users/x/src
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: my-app-namespace
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
