apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: TZ
          value: "Asia/Tokyo"
        - name: MARIADB_ROOT_PASSWORD
          value: "mdbroot"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: my-app-namespace
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
