name: Release to Production Environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/x
            docker compose down
            git remote set-url origin https://Kisana528:${{ secrets.GH_TOKEN }}@github.com/Kisana528/x.git
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build
